language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

env:
  matrix:
    - DB=mysql TYPO3_BRANCH=TYPO3_6-2 COVERAGE=0
    - DB=mysql TYPO3_BRANCH=TYPO3_7-4 COVERAGE=0
    - DB=mysql TYPO3_BRANCH=master COVERAGE=0
  global:
    secure: dm8+o7Ls4CYMB1kXeSDaFDC2Q8jEFGePx+w6XczzCwf3Gq9o36OIjH6yKRDx3cQp2gBPPeay6M+TH9V+ZQBv678lQDwFovYcDjqip3lrpQ1ny5Dsx0VeX17cZ/LE67wepLw0yXxdanZeMgFNvEXxPc8CG4iVpSWyL2e9TOJn2Fc=

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true
  include:
    - php: 5.6
      env: DB=mysql TYPO3_BRANCH=master COVERAGE=1
  exclude:
    - php: 5.4
      env: DB=mysql TYPO3_BRANCH=master COVERAGE=0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - s.kowalke@skyfillers.com

before_script:
  - cd ..
  - mkdir parallel && cd parallel && wget http://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2 && tar xvf parallel-latest.tar.bz2 -C . --strip-components=1 && ./configure && make && cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi
  - composer self-update
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv sf_filecollection_gallery typo3conf/ext/

script:
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit -c typo3conf/ext/sf_filecollection_gallery/Tests/Build/UnitTests.xml
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit --coverage-clover=unittest-coverage.clover -c typo3conf/ext/sf_filecollection_gallery/Tests/Build/UnitTests.xml
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      cp -R typo3conf/ext/sf_filecollection_gallery/.git .
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover;
    fi
